### ISSUE TITLE
List the minimum services required to connect to Oracle XE

### ISSUE THREAD

**Issue by timahenning** [saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#2]
![image](https://user-images.githubusercontent.com/48766586/131199896-afcb90eb-52ce-4ab3-998c-14a14659210a.png)

**Comment by timahenning** [comment]
If the student sets up Oracle the night before and then starts a new VM instance, listener service may not start.  They will get the following error.

![image](https://user-images.githubusercontent.com/48766586/131228577-cd67bdea-3961-45bb-8453-02a52f856e33.png)

**Comment by timahenning** [comment]
Need to add this troubleshooting step.  cmd window. lsnrctl status

![image](https://user-images.githubusercontent.com/48766586/131228616-12c1764c-6af5-4ca1-9583-7acd58e5d835.png)

**Comment by saimachi** [comment]
I added the lsnrctl status command image to the lab. I also explained how to start the listener manually if the student restarts the VM, as you mentioned.
