### ISSUE TITLE
Install pgAdmin should be moved to the BOL.

### ISSUE THREAD

**Issue by timahenning** [saimachi/MCW-Migrating-Oracle-to-Azure-SQL-and-PostgreSQL#8]
![image](https://user-images.githubusercontent.com/48766586/131252106-b0939bbf-e017-4844-bb09-736ff252f2de.png)

**Comment by saimachi** [comment]
This step is present in both the automated lab setup steps (ARM template) and the manual lab setup steps documents. It has also been removed from the main Oracle to PostgreSQL migration lab.
